### ISSUE TITLE
Turret Predictive Aiming

### ISSUE THREAD

**Issue by DenisLabrecque** [brihernandez/GunTurrets#7]
I'm going to work on this in a few days, but still it would be nice to have some sort of predictive functions included in the project where knowing the position of a target and the velocity of the shell, the target can be hit with the turret aiming at it.

**Comment by brihernandez** [comment]
This is out of scope for what this script is meant to handle.

The best kind of predictive aiming behavior will be dependent on the game and will have to make assumptions about how said projectile work. Another script (or a user-customized modification of this script) is should be giving this script a predictive location to aim at.
