### ISSUE TITLE
Limit Traverse Not Working in Some Situations

### ISSUE THREAD

**Issue by DenisLabrecque** [brihernandez/GunTurrets#8]
I am not sure why that is, but in my own project, even after limiting traverse, turrets still rotate through that limit. This may have to do with transforms and so on. Will report why that happened. Perhaps an error message is appropriate if setup is not done correctly.

**Comment by brihernandez** [comment]
This has been fixed in the new version of GunTurrets https://github.com/brihernandez/GunTurrets2
