### ISSUE TITLE
Boolean for Knowing when the Turret Is Aimed

### ISSUE THREAD

**Issue by DenisLabrecque** [brihernandez/GunTurrets#9]
A boolean indicating that the turret has reached its aimpoint would be super convenient for preventing shooting before the turret is ready to shoot.

**Comment by DenisLabrecque** [comment]
This could have a minimum angle away from the aimpoint as well, so that even if the turret diverges slightly every frame, it still has the chance to shoot.

**Comment by brihernandez** [comment]
This feature has been added in the new version of GunTurrets: https://github.com/brihernandez/GunTurrets2
